name: "Lint & Format"

on:
  push:
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: python3 -m venv .venv
      - run: ./.venv/bin/pip install black flake8 pre-commit
      - run: ./.venv/bin/black --check .
      - run: ./.venv/bin/flake8 .
